FROM jenkins/jenkins:lts
USER root
RUN chown -R jenkins:jenkins /var/jenkins_home/workspace

COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN jenkins-plugin-cli --plugins < /usr/share/jenkins/ref/plugins.txt

USER jenkins
